numtide/treefmt

- src/engine.rs
This should make it a bit easier when debugging to see which phases take a long time.
(I'm not sure `Δ` is the best description for what the phase time is ^^)
> Time phases individually

- .github/workflows/nix.yml
- LICENSE.md
- default.nix
- docs/LICENSE.md
- docs/default.nix
- docs/installation.md
- flake.nix
fixes #84
This PR will need `GITHUB_TOKEN` to be set up in this repo.
> Publish the docbook to GitHub Pages

- src/command/init.rs
- src/command/init_treefmt.toml
Avoid the big fat string literal
Thanks to @ldesgoui for the suggestion.
> init: use std::include_bytes

- src/customlog.rs
- src/engine.rs
> print files on --fail-on-change

- src/engine.rs
To try this PR:
1. edit `examples/rust/src/main.rs` by removing 1 syntax.
2. run `cargo run --`
> treat exit status code > 0 as an error

- docs/treefmt-configuration.md
- src/config.rs
- src/engine.rs
Closes #119
Adds an extra field to the config to support excludes that apply to all formatters
> Support global excludes

- src/engine.rs
> Handle the case where no formatter match path for stdin

- default.nix
- src/eval_cache.rs
- src/formatter.rs
- treefmt.toml
Speed up the zero case by not even invoking the underlying formatter.
Fixes #141
> formatter: noop on zero args

- README.md
- clippy.toml
- src/command/format.rs
- src/command/format_stdin.rs
- src/command/mod.rs
- src/engine.rs
Select formatters name to apply. Defaults to all formatters
refs #167
> cli: add --formatters option

- ci.sh
- module-options.nix
Add CI check so this actually gets exercised
> fix nixpkgs.withConfig

- src/command/mod.rs
- src/eval_cache.rs
Fix minor typos in doc comments.
> fix: minor typos

- docs/index.md
I tried to make it clearer for fresh eyes what this project is about
> docs: clearer landing page

- cli/cli.go
- cli/format.go
- cli/helpers_test.go
- cli/mappers.go
- main.go
> magic is bad; global state is magic → no package level vars; no func init
https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html
> cli: remove global state, init function usage

- format/glob_test.go
- nix/treefmt.nix
This helps demonstrate how our globbing works.
> test: add tests for glob matching

- flake.lock
- nix/devshell.nix
Remove the `unset PRJ_ROOT` hack.
> fix: update treefmt-nix

- .github/workflows/gomod2nix.yml
- nix/devshell.nix
Run `gomod2nix` on renovate bot PRs to update `gomod2nix.toml` automatically.
> feat: update gomod2nix on renovate bot prs

- flake.lock
- flake.nix
- nix/devshells/default.nix
- nix/devshells/renovate.nix
Re-use the package env instead.
Also fixes the annoying issue of $PRJ_ROOT handling. https://github.com/alecthomas/kong/issues/446
> feat: remove devshell

- config/config_test.go
- flake.nix
- nix/packages/treefmt/formatters.nix
- test/examples/treefmt.toml
> chore: use opentofu instead of terraform

- .mergify.yml
> ci: add mergify config

- cache/cache.go
> feat: add connect timeout to bolt db

- .github/workflows/golangci-lint.yml
> fix: golanci-lint workflow

- cache/cache.go
- cmd/format/format.go
- cmd/root.go
- cmd/root_test.go
- main.go
- stats/stats.go
Converts the stats package into a struct and removes the use of package global state.
> feat: remove globals from stats package

- .envrc
- cmd/init/init.toml
- config/config.go
- docs/content/getting-started/configure.md
- docs/content/getting-started/usage.md
- docs/content/reference/formatter-spec.md
- test/examples/treefmt.toml
> docs: update content to reflect latest changes

- docs/content/getting-started/configure.md
> docs: warn about exit with fatal level in on-unmatched

- .github/workflows/coverage.yml
- README.md
- nix/packages/treefmt/default.nix
Adjust the format a bit to be consistent with other projects
> README: new format

- .golangci.yml
- cmd/format/format.go
- cmd/root.go
- cmd/root_test.go
- config/config.go
- config/config_test.go
- format/formatter.go
- test/test.go
- walk/cache/cache.go
- walk/cached.go
- walk/filesystem.go
- walk/git.go
- walk/stdin.go
- walk/walk.go
Fixes https://github.com/numtide/treefmt/issues/484
> Enable more golangci-linter

- docs/content/.pages
- docs/content/guides/unmatched-formatters.md
> docs: add guide on handling unmatched formatters

- README.md
- cmd/init/init.toml
- cmd/root.go
- mkdocs.yml
- nix/packages/treefmt/default.nix
- test/examples/nixpkgs.toml
- test/examples/treefmt.toml
Makes the project's purpose a bit more explicit
> docs: change tagline

- go.mod
- go.sum
- nix/packages/treefmt/default.nix
> Termenv fix

- docs/hooks.py
- nix/packages/docs.nix
`os.system` happily returns an exit code if the command you're running fails:
```
$ python
>>> import os
>>> os.system("echo uh oh && exit 42"); print("This happened")
uh oh
10752
This happened
```
> chore(build): check for errors when running command

- cmd/format/format.go
> fix: move path resolution logging to debug instead of error

- README.md
Small PR - Commit 3828aaf226c1d3673d809704938931315c819a75 moved `formatter-spec.md`. This PR adjusts sources to changes.
> docs: update formatter spec

- cmd/format/format.go
- cmd/root_test.go
> Fix when tree root is symlink

- docs/site/reference/formatter-spec.md
Just a bunch of nits. Read the commits independently.
> Formatter spec consistency nits
