numtide/treefmt

README.md, src/command/format.rs, src/command/init.rs, src/command/mod.rs, src/customlog.rs, src/engine.rs, src/eval_cache.rs, src/formatter.rs, src/lib.rs, src/main.rs
Instead of calling CLOG directly, use the "log" crate on the producer
side, and then plug CLOG as a consumer. This allows for some nice
decoupling and the log macros are also nicer on the eye.
--log-level has disappeared for now
Thanks to @ldesgoui for the suggestion.
=> customlog: use the log facade

src/engine.rs, src/eval_cache.rs
Hey, as per my comments on twitter, this would be one way to reduce the number of allocations in `eval_cache`, I'll sprinkle some comments on the diff to help making the changes understandable, feel free to ask any questions.
=> Code suggestion: Mutate the eval cache instead of cloning it

Cargo.lock, Cargo.toml, README.md, src/command/format_stdin.rs, src/command/mod.rs, src/engine.rs
A first pass at making --stdin work.
There is quite a bit of repetition with the normal mode but I didn't feel like factoring things too much out at the moment.
Regarding the tempfile, I was looking at https://docs.rs/tempfile/3.0.7/tempfile/ but it doesn't support specifying the file extension.
=> implement --stdin

src/formatter.rs
fixes #103 
Show `stdout` and `stderr` of the formatter when it errors out.
To simulate a formatter error I have been using:
```diff
diff --git a/treefmt.toml b/treefmt.toml
index 2b5fb94..99f55e6 100644
--- a/treefmt.toml
+++ b/treefmt.toml
@@ -1,7 +1,8 @@
[formatter.python]
-command = "black"
+command = "bash"
+options = ["-c", "echo $1; >&2 echo This is an error; exit 1", "--"]
includes = ["*.py"]
[formatter.elm]
```
This results in the following output:
```bash
🐛 [DEBUG]: Error using formatter #python:
• [STDOUT]:
/home/basile/dev/treefmt/examples/python/main.py
• [STDERR]:
This is an error
ℹ️ [INFO]: #elm: 1 files processed in 38.89ms
ℹ️ [INFO]: #rust: 13 files processed in 73.00ms
⛔ [ERR]: #python's formatter failed: exit status 1
```
=> Report formatter output on error

devshell.toml, examples/haskell/Foo.hs, examples/haskell/Nested/Foo.hs, examples/haskell/treefmt.toml, src/lib.rs, treefmt.toml
As discussed, since all path is absolute, then we should always expand the path in the `treefmt.toml`
fixes #102 and #82
=> Always expanding the path given in the treefmt.toml

.github/workflows/nix.yml
The cache was converted to using auth tokens
=> ci: use the cachix auth token instead

src/engine.rs
We don't want to format files outside the directory, and if the symlink
destination is in the repo, it'll be matched when iterating over it.
Fixes #122.
=> engine: skip over symlinks

default.nix, flake.lock, flake.lock.nix, flake.nix
- Naersk has the annoying property to pin nixpkgs as a dep
- Nixpkgs mostly is a _core_ dependency that it is worth auditing duely
(e.g. to avoid cache mismatches and other spourious errors)
- Every usage of naersk adds a another "spurious" nixpkgs dep somewhere
to the flake lock. That makes auditing less straight forward.
=> Trade in naersk for a newer version of nixpkgs

src/engine.rs, src/eval_cache.rs, src/lib.rs
File mtimes is actually not precise enough in all cases. By also
tracking the file sizes it should reduce the instances of
false-positives.
See #46
=> cache: also track file sizes

README.md, src/command/format.rs, src/command/mod.rs, src/engine.rs
This is useful for CI where you don't care about eval caching. And avoid
the issue described in #156.
=> cli: add --no-cache option

examples/python/virtualenv_proxy.py, flake.lock, flake.nix
- Allow `aarch64-darwin` (tested using `nix build`) and others allowed by `eachDefaultSystem`
- Update flake-utils so that `eachDefaultSystem` includes this architecture
- Update nixpkgs to fix https://github.com/NixOS/nixpkgs/issues/140774
=> Allow macOS M1

default.nix
=> nix: move ci dependencies to the devShell

contrib/pre-commit
This is working towards #78 . In the end that script would be shipped
with the treefmt binary, but for now let's just test it out.
=> add pre-commit contrib script

src/config.rs
This adds support for a configuration file `.treefmt.toml` in addition to the default `treefmt.toml`. If both are found, only the `treefmt.toml` is accepted. I could also raise an error in that case.
Most of the formatters support dotfiles as configuration file (which I prefer), I figured out that the project could benefit from this option.
=> Add support for `.treefmt.toml`

default.nix, src/command/format.rs, src/command/format_stdin.rs, src/eval_cache.rs
Don't touch $HOME unless needed.
Fixes #173.
=> lazily create the cache directory

.envrc, default.nix, flake.nix
https://github.com/numtide/treefmt/pull/169#issuecomment-1219213800
=> Make `treefmt.withConfig` work independent of $PRJ_ROOT

flake.lock, flake.nix
https://twitter.com/zimbatm/status/1529504445201006592
Ultimately, this would pave the way for exposing a `flakeModule` when upstreaming https://github.com/srid/treefmt-flake here ... 
Note:
- This PR also updated `nixpkgs` for `nixpkgs.lib.systems.flakeExposed`
=> Switch to `flake-parts`

.envrc, default.nix, flake.lock, flake.nix, module-options.nix
This is useful if you want to configure treefmt with nix, and precisely
pass all the commands from nixpkgs.
=> add treefmt.withConfig

src/engine.rs
Changes the current output...
```
traversed 1222 files
matched 677 files to formatters
left with 2 files after cache
of whom 0 files were re-formatted
all of this in 173.44ms
```
...to a more concise format
```
0 files changed in 173ms (processed 1222, matched 677, cache misses 2)
```
Closes #125
=> feat: more concise stats

src/main.rs
Info is meant to inform the user. In that case, we want to show how much time each formatter is taking, because it's good for the ecosystem to be aware of how slow each formatter is.
=> change default log level to info

src/engine.rs, src/formatter.rs
Display what it was looking for, so it's easier to debug.
Before:
Failed to load formatter #python due to error: cannot find binary path
After:
Failed to load formatter #python: could not find 'black' on PATH
This should help with errors like https://github.com/numtide/treefmt-nix/issues/27
=> improve the formatter load error

Cargo.lock, Cargo.toml, src/command/mod.rs, src/main.rs
=> feat: clap integration

src/config.rs, src/engine.rs
With the following config:
```toml
[formatter.cpp]
command = "clang-format"
options = ["-i"]
includes = ["*.cpp"]
```
`treefmt --stdin foo.cpp < foo.cpp` would error:
```
[ERROR] original tempfile has been replaced at path "/home/oleh/src/treefmt/_tmpoZwnEJfoo.cpp"
```
..since `clang-format` creates its own tempfile and then moves it into our own tempfile,
replacing it and causing `tmpfile.reopen()` to fail.
=> fix treefmt --stdin when changes are moved into tempfile

src/command/format_stdin.rs, src/command/mod.rs
=> Don't ignore --config-file when using --stdin

flake.lock, flake.nix
This commit introduces a new convention that allows consumers of a flake to control systems the flake is built with.
One of the core issues of flakes is that the list of systems that a flake is evaluated with is internal to the flake. Some projects can technically build with more platforms, but to change this, the user has to fork or submit a patch to change the list. Conversely, as a consumer of a flake, you might not care of evaluating the flake with all of the systems, and that list cannot be reduced.
To work around that issue, we introduce a new convention: 
1. If the `systems` input exists, it MUST point to a nix file. 
2. That file SHOULD be named `flake.systems.nix`.
3. That file MUST contain a list of supported systems (list of strings)
4. That input MUST be used by the flake to …
=> flake: expose the list of supported systems

src/engine.rs, src/formatter.rs
Add tests for the run engine. A particular focus of these tests are
allowing assertions of the relationships between:
- configuration
- directory structure
- walked files
- matched files
What has been done: 
- refactored parts of the run function into it's own methods
- tested these methods
- goal is a pure refactor and no behavioral changes
`cargo tarpaulin`: 
```
src/engine.rs: 69/200 +34.50%
src/formatter.rs: 36/74 +48.65%
```
=> chore: add tests for the run engine

docs/treefmt-configuration.md
Closes #242.
Also snuck a small typo fix in there.
=> docs: fix inconsistent `includes` documentation

ci.sh, src/command/mod.rs
Fix flaky tests that use `std::env::set_var`.
`std::env::set_var` is not safe to be used in parallel.
Add `#[ignore]` statements to these tests.
Add an extra test step to `ci.sh`, as I don't think there is a better way mark certain tests as single threaded only.
Reproducer:
```bash
for _ in {0..100}; do
cargo t current_dir || exit 1
done
```
Will fail very fast.
Doesn't fail:
```bash
for _ in {0..100}; do
cargo t current_dir_prefers_pwd_env_var || exit 1
cargo t current_dir_uses_dereferenced_path_when_pwd_env_var_not_set || exit 1
done
```
Reference: https://github.com/rust-lang/rust/issues/27970
=> Fix flaky tests that use `std::env::set_var`

docs/formatters.md
- adds typst and typstfmt to the list of known formatters in the docs
=> docs: add typst and typstfmt

src/engine.rs
This PR changes checking missing formatters logic like the below.
- If some formatters are specified with `-f`/`--formatters`, check whether they are defined in config and executable.
- If not specified, check whether all formatters are executable
I think it will resolve #210.
If something goes wrong, feel free to point it out. Thank you.
=> fix: enable to select some formatters without `--allow-missing-formatter`

docs/integrations.md
`null-ls` is deprecated, and `none-ls` seems to be the maintained fork.
=> docs: update neovim integration

src/engine.rs
From the website I'd have thought this would be done already, but after running it over Nixpkgs it turns out it's not.
Parallel formatting seems to originally have been implemented by @basile-henry in https://github.com/numtide/treefmt/pull/17, which subsequently didn't make it in @zimbatm's https://github.com/numtide/treefmt/pull/68. While https://github.com/numtide/treefmt/pull/71 attempted to re-implement it, it only runs each _formatter_ in parallel, but not individual _files_ for the same formatter.
This PR fixes that, making each chunk of 1024 files run in parallel (so no extra parallelism if there's less than that number of files).
I tested this with
```toml
[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = [ "*.nix" ]
```
with https://github.com/NixOS/nixfmt on …
=> feat: run the same formatter in parallel for many files

src/engine.rs
Ran treefmt on itself.
The current main branch has failing `ci` because of it.
I have not yet looked into why it hasn't been caught prior to merging.
Edit: #282 doesn't seem to have the same checks.
=> chore: treefmt

cli/cli.go, cli/format_test.go
Preserves backwards compatibility with v1
=> fix: -f short flag for specifying formatters

flake.lock, flake.nix
It now supports freeform type for settings allowing us to pass through pipeline options.
=> feat: switch back to numtide/treefmt-nix

cli/format.go, cli/format_test.go
When multiple formatters need to operate on the same path they must do so as part of a pipeline to avoid concurrent modification and non-deterministic issues.
This change will detect when a path has matched against more than one pipeline and error out indicating the pipelines involved.
=> Error out when a path matches multiple formatters

.github/workflows/gh-pages.yml
We currently publish an update when we merge to `main`. This means new functionality that is not yet released is being talked about on the docs site.
This restricts deploying to github pages to releases.
=> fix: restrict github pages publication to releases

.goreleaser.yaml
This is to prevent noise until we have a stable 2.x
=> feat: configure goreleaser to mark releases as pre-release

cli/cli.go, cli/format.go, cli/format_test.go, cli/helpers_test.go, cli/mappers.go, docs/usage.md, main.go
By default, if a path does not match any formatter a log message at WARN level will be emitted. A user can change this by providing the `--on-unmatched` or `-u` flag and specifying a log level `debug,info,warn,error,fatal`.
If `fatal`, the process will exit with an error on the first unmatched path encountered.
```
❯ nix fmt -- -c -u fatal
traversed 24 files
emitted 24 files for processing
matched 0 files to formatters
formatted 0 files in 514.925µs
treefmt: error: no formatter for path: /home/brian/Development/com/github/numtide/treefmt/.env
```
```
❯ nix fmt -- -c -u error
ERRO format: no formatter for path: /home/brian/Development/com/github/numtide/treefmt/.env
ERRO format: no formatter for path: /home/brian/Development/com/github/numtide/treefmt/.envrc
ERRO format: no formatter for …
```
=> --on-unwatched

cli/cli.go, cli/format.go
Restore the treefmt 1.x behaviour where it would search for the tree root by recursively searching for the treefmt.toml file up the filesystem, starting from the current directory.
The `--tree-root-file` option will be useful to remove this bash wrapper: https://github.com/numtide/treefmt-nix/blob/2fba33a182602b9d49f0b2440513e5ee091d838b/module-options.nix#L116-L135
Fixes #308
=> cli: search for the tree root by default

cli/cli.go, cli/format.go, cli/format_test.go, config/config_test.go, format/formatter.go, nix/treefmt.nix, test/examples/treefmt.toml
Separates global excludes processing from `Formatter.Wants`. This removes redundant processing of global excludes in each `Formatter.Wants` call.
If a file has been globally excluded, we do not emit an `on-unmatched` log message. This should help reduce noise as reported in #317.
=> feat: improve unmatched logic

cli/format_test.go, format/formatter.go, nix/devshell.nix, stats/stats.go, walk/filesystem.go, walk/git.go
golangci-lint doesn't follow the treefmt spec so it can't be integrated
with treefmt unfortunately.
=> chore: do a golangci-lint pass

cli/format.go, format/formatter.go
Tune the error handling to fail more gracefully. And restore similar behaviour to treefmt 1.x
Fixes #316
=> Softer cancel

README.md
This PR makes a small change to the docs to include a mention to a [vscode extension](https://marketplace.visualstudio.com/items?itemName=ibecker.treefmt-vscode) that I wrote.
- added section `IDE integration`
- mentions [treefmt-vscode](https://github.com/isbecker/treefmt-vscode)
- changes `Upcoming features` on IDEs to "More IDE integration", now reflecting that there is some IDE integration
=> docs: adds information regarding IDE integration in vscode

cli/format.go
Otherwise `--no-cache` still fails to open the cache.
Part of #327.
=> fix: only try opening the cache if cache is enabled

docs/configure.md
Fixes config example showing how to configure global excludes properly. 
=> doc: fix global excludes config example

config/config.go, config/formatter.go
The toml marshaller appears to be permissive with case when reading. This makes the case explicit with `toml:""` tags for everything. 
=> fix: configure toml keys for config fields

cli/format.go
=> feat: if we can't open the cache, fallback to no cache

cli/helpers_test.go, docs/.vitepress/config.mts, docs/about.md, stats/stats.go
Rounds elapsed time to nearest millisecond and changes stats phrasing to make it clearer.
```console
❯ nix fmt -- -c 
traversed 97 files
emitted 97 files for processing
formatted 49 files (0 changed) in 551ms
```
Close #337
Close #339 
=> Improve summary stats

cache/cache.go, cli/cli.go, cli/format.go, cli/format_test.go, format/formatter.go
Separates out the logic for detecting changes from the logic for updating the cache, fixing the case where both `--fail-on-change` and `--no-cache` are enabled.
Closes #343
=> fix: --no-cache

cli/format.go, cli/format_test.go, flake.lock, nix/packages/treefmt/formatters.nix, test/examples/treefmt.toml, test/examples/yaml/test.yaml, test/temp.go, walk/walker.go
We were using whatever precision the underlying file system was giving us, and in some cases that can be very detailed. Some formatters mess with the mod time, but not to the same precision (e.g. dos2unix).
POSIX also specifies that mod time should be EPOCH (second) precision.
This change brings us back in line with how 1.x worked, and should resolve issues with false fail on change errors.
Closes #342
=> fix: use second precision when comparing file mod times

cli/cli.go, docs/usage.md
PRJ_ROOT is coming from the https://github.com/numtide/prj-spec and was used in treefmt 1.x
Fixes #353
=> fix(cli): restore PRJ_ROOT env var

cli/cli.go, cli/format.go
This restores treefmt v1 compatibility by also searching for the dot prefixed version of the config file.
Fixes #355
=> feat: search for .treefmt.toml

cli/format_test.go, walk/git.go
This can happen if a user removes a file from the filesystem and that change hasn't been staged yet.
We log a warning when this happens and continue.
Closes #364
=> fix(git): gracefully handle a file in the index but not in the filesystem

cli/format.go
By default, we log the changed file at debug level. If the `--fail-on-change` flag has been provided, we log the changed file at error level.
This is to surface issues better in CI pipelines for example.
Closes #380
=> feat: log changed files at error level when --fail-on-change is enabled

cli/format_test.go, cli/helpers_test.go, config/config_test.go, test/examples/treefmt.toml, walk/git.go
=> fix: Do not exclude executables in git walker

cli/cli.go, cli/format.go, docs/contributing.md, format/formatter.go, format/task.go
When applying a sequence of formatters, continue applying the batch to successive formatters even if one of the stages fails. 
Closes #316
=> apply all formatters even when there's errors

cli/format.go, cli/format_test.go
The contract seems to be that the `walkFilesystem` goroutine is
responsible for closing `f.filesCh`, but before this change, there were
codepaths that could result in the gorouting exiting without closing
`f.filesCh`. That shouldn't be possible anymore, so long as we keep this
statement at the top of the function =)
This fixes https://github.com/numtide/treefmt/issues/406
=> Avoid hanging: ensure we always close `f.filesCh`

.github/workflows/golangci-lint.yml, cmd/format/format.go, cmd/root_test.go, config/config.go, walk/cached.go, walk/cached_test.go, walk/filesystem.go, walk/filesystem_test.go, walk/git.go, walk/git_test.go, walk/stdin.go, walk/type_enum.go, walk/walk.go
Changes how we handle paths which are provided as arguments:
- if it's a file, we attempt to format it based on the matching options
- if it's a directory, we traverse it using the provided walk type
This is more consistent with what a user expects and makes it easier to integrate with tools such as `none-ls`.
Close #435
=> Improve path argument handling

cmd/format/format.go, cmd/root_test.go, test/temp.go
This fixes a few issues with both relative and absolute paths:
- Previously, treefmt refused to format any files passed as absolute paths, regardless of if they were in tree or not: https://github.com/numtide/treefmt/issues/442
- Previously, treefmt would treat relative paths as relative to the project root, which is not ideal if you're in a subdirectory and you just want to format the file you're right next to: https://github.com/numtide/treefmt/issues/443
- There was even a test asserting this behavior. I changed it to reflect the updated behavior.
- treefmt's handling of paths outside of the project root was a bit inconsistent: https://github.com/numtide/treefmt/issues/444
=> fix: correct handling of absolute and relative paths

cmd/format/format.go, cmd/root_test.go
See https://github.com/numtide/treefmt/pull/440 for the last attempt to
do this because (at the time) this "is the file in the tree root?" check
relied upon checking for concrete files in the filesystem. As of
https://github.com/numtide/treefmt/commit/ff3de21a2b35a3218e845609ccd5a6a7215e9fdc,
that's longer the case, so we can make this code a bit more consistent.
=> fix: normalize and enforce stdin paths as well

docs/formatter-spec.md
Some formatters are aware of VCS systems like git, and "helpfully" skip over files that are not tracked by the VCS system. This doesn't play nicely with treefmt, because treefmt expects to be able to generate tempfiles (which are not tracked by a VCS) and pass them to the formatter.
=> Clarify in the spec that the formatter MUST process the given files

.golangci.yml, build/build.go, cmd/format/format.go, cmd/init/init.go, cmd/root.go, cmd/root_test.go, config/config.go, config/config_test.go, format/cache.go, format/formatter.go, format/glob.go, format/glob_test.go, format/task.go, stats/stats.go, test/temp.go, walk/cache/bucket.go, walk/cache/cache.go, walk/cached.go, walk/cached_test.go, walk/filesystem.go, walk/filesystem_test.go, walk/git.go, walk/git_test.go, walk/stdin.go, walk/walk.go
Applies more stringent `golangci-lint` rules to the repository, borrowed from https://github.com/nix-community/go-nix.
Also fixes a bug where we were not returning errors when calling `walk.Reader.Read()` in `cmd/format`
=> feat: more stringent golangci-lint rules

cmd/format/format.go, cmd/root_test.go, format/formatter.go
We try to apply formatters to all files on a best-effort basis, continuing if formatting any particular batch of files fails.
This fix ensures that if any formatting errors occur, the process will exit with an error.
Closes #450
=> fix: exit with error if any formatters fail

cmd/root_test.go, test/examples/emoji 🕰️/README.md, walk/filesystem_test.go, walk/git.go, walk/git_test.go
`git ls-files` was providing some `"..."` quoted paths when it encountered emojis in the file/dir name.
Running them through `strconv.Unquote` fixes things.
Fixes #485
=> fix: non-ascii paths in git walker

format/formatter.go
In this case the command was empty:
```
> Error: failed to create composite formatter: failed to initialise formatter mypy-: formatter command not found in PATH
```
=> better error if command cannot be found

cmd/format/format.go, cmd/root.go, cmd/root_test.go, config/config.go, config/config_test.go, docs/content/getting-started/configure.md, docs/content/guides/unmatched-formatters.md, mkdocs.yml, stats/stats.go
I've made some changes to how verbose we are being:
- **feat: log the config file used at DEBUG level instead of INFO**
- **feat: print stats to stderr instead of stdout**
- **feat: change default log level for unmatched to INFO instead of WARN**
- **feat: add a quiet flag to suppress all output except for errors**
Closes #501
=> Verbosity changes

cmd/format/format.go, cmd/root_test.go
When reviewing #511, I noticed there was some shadowing of variables and edge cases which were not being handled gracefully.
=> feat: improve error handling in format Run method

cmd/root_test.go, config/config.go
As the title suggests. 
Recently discovered in https://github.com/numtide/treefmt-nix that names with `/` could be passed through and would break execution. This enforces simple formatted names in config and when passing as `formatters` arg. 
Also fixes misuse of the assertions API.
=> Enforce formatter name doesn't contain bad characters

.github/workflows/update-vendor-hash.yml, nix/packages/treefmt/default.nix
I forgot when removing `gomod2nix` that we would need an automatic way of updating the vendor hash for renovate PRs. This adapts a pattern from https://github.com/Mic92/ssh-to-age/blob/main/.github/workflows/update-vendor-hash.yml
=> feat: add workflow to automatically update vendorHash

.github/workflows/update-vendor-hash.yml
It was targetting dependabot not renovatebot
=> fix: update vendor hash workflow

cmd/completions.go, cmd/root.go, docs/content/getting-started/usage.md, nix/packages/treefmt/default.nix
- disables default `completion` cobra sub-command
- adds a `--completion [bash|zsh|fish]` flag which will generate shell completions using cobra's built-in support
- adds `installShellCompletion` to the `treefmt` package (this will need added to the nixpkgs entry after release)
The completions are static and address the first half of #529.
=> fix: shell completions

flake.nix
I've never seen the project called "Treefmt" anywhere, and we changed the tagline back in
https://github.com/numtide/treefmt/commit/5892f1abcdea99ebf46a011233670c046ed61757.
=> chore(flake): fix name + tagline

nix/packages/treefmt/default.nix
Inherit the `withConfig` and `buildConfig` wrapper functions added in https://github.com/NixOS/nixpkgs/pull/390147
Fixes #558
If the current nixpkgs revision does not have these attrs, a sane error message is thrown when attempting to use them.
```
nix-repl> :lf .
nix-repl> packages.x86_64-linux.treefmt.withConfig
error:
… while evaluating the attribute 'x86_64-linux.treefmt.withConfig'
… while evaluating a branch condition
error: Accessing `withConfig` requires a nixpkgs revision that has `treefmt.withConfig`.
```
I've tested this with and without `nix flake lock --override-input nixpkgs 'github:nixos/nixpkgs/nixos-unstable-small'`. With the newer nixpkgs revision the wrapper functions seem to work correctly.
The `treefmt` argument passed is overridden to refer to …
=> feat: add `withConfig` & `buildConfig` from nixpkgs

cmd/root_test.go, walk/git.go, walk/git_test.go
This was quick enough to implement and, at face value, feels appropriate. 
But my spidey senses are tingling, and I can't quite understand why. 
@zimbatm, @jfly: why might this be the wrong thing to do?
Closes #557
=> feat: traverse untracked files in git walker

nix/packages/treefmt/default.nix
This is required by `buildConfig` and `withConfig` since https://github.com/NixOS/nixpkgs/pull/406685.
=> feat: add `evalConfig` from nixpkgs

nix/packages/treefmt/default.nix
Sorry, this was bugging me last time I looked at this code.
We don't actually care if `__functionArgs.treefmt` is null (it'll always be `true` or `false`). We actually care if the attr is present.
IIRC, when I first wrote that line I didn't know you could use a nested attrpath on the RHS of the `?` operator, so I resorted to misusing `or` instead.
=> refactor: simplify one line of nix code

cmd/init/init.toml, cmd/root_test.go, config/config.go, docs/site/getting-started/configure.md, jujutsu/jujutsu.go, nix/packages/treefmt/default.nix, test/config/jj/config.toml, test/test.go, walk/jujutsu.go, walk/jujutsu_test.go, walk/type_enum.go, walk/walk.go
This PR introduces a new Jujutsu walker to numtide/treefmt, modeled after the existing Git walker but tailored to Jujutsu repositories. Key differences include:
- The list command does not update the index automatically, so untracked files must be explicitly added via `jj` commands.
This addition enables proper handling of Jujutsu ignore rules without requiring co-located Git repos, improving integration and file traversal accuracy for Jujutsu users.
I lack Go experience and primarily copied, and adapted the existing Git walker by adjusting commands. I would welcome guidance or collaboration to develop a more idiomatic and robust implementation.
=> feat: add jujutsu walker

docs/site/reference/formatter-spec.md
I opted to put this in what felt like a logical order, but it does mean that other rules ("Idempotent" and "Reliable") got renumbered.
How do we feel about that? IMO, we should probably have version number for the spec.
The naming and styling of the changes here are intended to be consistent with https://github.com/numtide/treefmt/pull/609
=> chore: require that formatters exit nonzero on error

cmd/root_test.go, format/formatter.go, nix/devshells/default.nix, nix/packages/treefmt/formatters.nix, test/examples/just/justfile, test/examples/treefmt.toml, walk/cached.go, walk/filesystem_test.go, walk/git_test.go, walk/jujutsu_test.go, walk/stdin.go, walk/walk.go
=> Introduce tmp path to better handle stdin

cmd/root_test.go, test/test.go
I found that `TestGit` (and `TestJujutsu`, which was copied from `TestGit`) were failing intermittently. This took me some time to track down: the issue is an interaction between a few things:
- This test configures a formatter to run on all files (`"*"`), which importantly includes the `treefmt.toml` file at the root of the temp test project
- This test invokes treefmt with `withConfig(configPath, cfg)`. Under the hood, `withConfig` always writes to the `treefmt.toml` config file, which (possibly) means updating the mtime of `treefmt.toml` file.
- treefmt computes cache signatures using mtimes at 1-second granularity (presumably because this the only cross filesystem compatible option).
In effect, if the test ran quickly (under 1 second), then `treefmt.toml` would get formatted exactly 1 …
=> chore: fix flaky tests
